package game

const (
	HEARTS          = "❤️"
	DIAMONDS        = "♦️"
	CLUBS           = "♣️"
	SPADES          = "♠️"
	PAIR            = "PAIR"
	HIGH_CARD       = "HIGH_CARD"
	TWO_PAIR        = "TWO_PAIR"
	THREE_OF_A_KIND = "THREE_OF_A_KIND"
	FOUR_OF_A_KIND  = "FOUR_OF_A_KIND"
	FLUSH           = "FLUSH"
	STRAIGHT        = "STRAIGHT"
	STRAIGHT_FLUSH  = "STRAIGHT_FLUSH"
	ROYAL_FLUSH     = "ROYAL_FLUSH"
	TWO             = "TWO"
	THREE           = "THREE"
	FOUR            = "FOUR"
	FIVE            = "FIVE"
	SIX             = "SIX"
	SEVEN           = "SEVEN"
	EIGHT           = "EIGHT"
	NINE            = "NINE"
	TEN             = "TEN"
	JACK            = "JACK"
	QUEEN           = "QUEEN"
	KING            = "KING"
	ACE             = "ACE"
)
